import Theme from '@/providers/themeProvider'
import './globals.css'

import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Header from '@/layouts/general/header/header'
import Footer from './../layouts/general/footer/footer';
import Newsletter from '@/layouts/general/newsletter/newsletter'

const robotoMono = localFont({
  src: [
    {
      path: './Roboto_Mono/static/RobotoMono-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './Roboto_Mono/static/RobotoMono-Medium.ttf',
      weight: '500',
      style: 'medium',
    },
    {
      path: './Roboto_Mono/static/RobotoMono-Bold.ttf',
      weight: '700',
      style: 'bold',
    },
  ],
  display: 'swap',
})


export const metadata: Metadata = {
  title: 'Home Finder Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={robotoMono.className}>
      <body>
        <Theme>
          <Header />
          {children}
          <Newsletter />
          <Footer />
        </Theme>
      </body>
    </html>
  )
}
