import { Providers } from '@/providers/providers';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from "next/font/google";
import Navbar from '@/components/navbar/navbar';
import Footer from '@/components/footer/footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Home Finder Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <div className="container">
          <Providers>
            <Navbar />
            {children}
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  )
}
